baseURL = "https://security.profileo.com"
languageCode = "fr-fr"
title = "Profileo security"
theme = "hugo-whisper-theme"
copyright = "Copyright 2023 - Profileo.com est une marque du groupe Profileo"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
summaryLength = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

defaultContentLanguage = 'fr'
[languages]
  [languages.fr]
    languageCode = 'fr-FR'
    languageName = 'Français'
    languageNameShort = 'fr'
    languageFlag = "🇫🇷"
    title = 'Profileo Sécurité'
    weight = 1
    copyright = "Copyright 2023 - Profileo.com est une marque du groupe Profileo"
    [languages.fr.menu]
[[languages.fr.menu.main]]
      name = "Accueil"
      url = "/fr/"
      weight = 1
[[languages.fr.menu.main]]
      name = "FAQ"
      url = "/fr/faq"
      weight = 2
[[languages.fr.menu.main]]
      name = "Annonces"
      url = "/fr/advisories"
      weight = 3
[[languages.fr.menu.main]]
      name = "CVE"
      url = "/fr/cve"
      weight = 4
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    languageNameShort = 'en'
    languageFlag = "🇬🇧"
    title = 'Profileo security'
    weight = 2
    copyright = "Copyright 2023 - Profileo.com is a brand of the Profileo Group"
    [languages.en.menu]
[[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
[[languages.en.menu.main]]
      name = "FAQ"
      url = "/faq"
      weight = 2
[[languages.en.menu.main]]
      name = "Advisories"
      url = "/advisories"
      weight = 3
[[languages.en.menu.main]]
      name = "CVE"
      url = "/cve"
      weight = 4


[params]
  google_analytics_id="G-FKJVT9BC01"

  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Explore Profileo Security's advisories, vulnerability reporting guidelines, and security policies. Stay informed and collaborate with our security team to enhance the safety of the digital environment."
    meta_og_title = "Profileo security"
    meta_og_type = "website"
    meta_og_url = "https://security.profileo.com"
    meta_og_image = "https://www.profileo.com/img/eocontent/1589354942_laptop.webp"
    meta_og_description = "Profileo security."
    meta_twitter_card = "summary"
    meta_twitter_site = "@profileo"
    meta_twitter_creator = "@profileo"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
